title: "John Mohd Wani – Research Portfolio"
description: "Personal academic website built with Jekyll and Minimal Mistakes."
url: "https://johniitr.github.io"
baseurl: ""
remote_theme: "mmistakes/minimal-mistakes"
minimal_mistakes_skin: "air"
plugins:
  - jekyll-remote-theme
  - jekyll-include-cache
  - jekyll-paginate
  - jekyll-feed
  - jekyll-seo-tag

author:
  name   : "John Mohd Wani"
  avatar : "/assets/images/WaniJohn.jpg"
  bio    : "Researcher in Earth System Science."

  links:
    - label: "Google Scholar"
      icon: "fas fa-graduation-cap"
      url: "https://scholar.google.com/citations?user=2K-7VUMAAAAJ&hl=en"
    - label: "GitHub"
      icon: "fab fa-github"
      url: "https://github.com/Johniitr"
    - label: "University of Trento" 
      icon: "fas fa-university" 
      url: "https://www.centro3a.unitn.it/en" 
paginate: 5
paginate_path: /page:num/
